feat: support pushing a commit to other repository and branch (#123)
* feat: support pushing a commit to other repository and branch

* ci: set up CI

* ci: fix permissions

* chore: update dependencies

* ci: fix workflows

* chore: configure pinact

* fix: fix a bug that action fails if inputs.config is empty

* ci: update release-js-action

* fix: fix the error of post step

```
Error: The template is not valid. csm-actions/securefix-action/pr/123/server/prepare/action.yaml (Line: 50, Col: 12): Error reading JToken from JsonReader. Path '', line 0,
```

* fix: make the input pullRequest optional

* fix: fix the input branch of commit-action

* fix: fix the default repsository and branch

* fix: return error if repository or branch is set but config isn't set

* fix: fix a bug that notify doesn't work

* fix: fix source

* fix: return

* fix: add fail_if_changes

* fix: rename source and destination to client and push

* feat: support creating a pull request

* chore: fix pinact error

* fix: fix

* fix: replace description with body

* fix: fix typo

* fix: output parameters for debug

* fix: fix if condition

* fix: output values for debug

* fix: fix if

* fix: fix typo

* fix: fix expression

* fix: set pr base branch

* fix: validate pull request parameters in client side

* feat: support posting a pull request comment

* fix: trim spaces

* docs: fix example

* fix: output repository and branch even if repository and branch aren't passed

* fix: throw error immediately if config isn't set

* feat: create a GitHub access token to push a commit to the other repository

* fix: fix typo

* fix: fix issue token

* fix: fix a bug that labels, assignees, and reviewers aren't set

* style: fix typo

* fix: replace octokit with github

* fix: fix a bug that it fails to create labels

* fix: output info log

* debug

* fix: add team_reviewers

* fix: fix permissions

* fix

* docs: update the document

* chore: generate JSONSchema

* [autofix.ci] apply automated fixes

* fix: add a newline at the end of file

* feat: add an action to validate config

* feat: support reading config from a file

* fix: fix validation of inputs

* docs: fix

* chore: fix .pinact.yaml

* docs: update

* docs: update

* docs: update

* chore: fix .pinact.yaml

* docs: update

* docs: fix typo

* fix: rewrite steps with JavaScript action

* fix: fix warning

* fix: fix import @actions/github

* fix: fix a trivial bug

* fix: fix outputs

* fix: fix outputs

* fix: call function

* fix: fix check of pull request

* fix: pass workflow_name

* fix: stop checking if the commit sha is latest

* fix: output metadata

* fix: fix typo

* fix: fix output of metadata

* fix: support old client

* feat: add the input files

* chore: update release-js-action to v0.1.7

* fix: add the input files

* fix: fix output name

* fix: fix log

* fix: upload hidden files

* chore: update actions

---------

Co-authored-by: autofix-ci[bot] <114827586+autofix-ci[bot]@users.noreply.github.com>